import "./globals.css";

export const metadata = {
  title: "Frontend Mentor | Job Listings",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-[100vw] min-h-[100vh] bg-Background font-primary font-[500] overflow-x-hidden`}>{children}</body>
    </html>
  );
}
